name: Custom Event Workflow
on:
  repository_dispatch:
    types: [shariff_event]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Print Payload Shariff
        run: echo "Received payload:${{ toJson(github.event.client_payload) }}"
