name: Custom Event Workflow
on:
  repository_dispatch:
    types: [shariff_event]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Name Payload Shariff
        run: echo "Echo Received payload to Shariff:${{ toJson(github.event.client_payload) }}"
